name: shelfo
description: "Shelfo is an inventory and repair management system"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # image
  flutter_svg: ^2.2.4

  # state management
  provider: ^6.1.5+1

  # data base
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4

  # formatter
  intl: ^0.20.2

  # image picker
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1

  # pdf
  pdf: ^3.12.0
  printing: ^5.14.3
  share_plus: ^13.1.0

  # responsive
  flutter_screenutil: ^5.9.3

  # charts
  fl_chart: ^1.2.0

  # notifications
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  hive_ce_generator: ^1.11.1
  build_runner: ^2.12.2
  flutter_launcher_icons: ^0.14.4
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/


  # custom fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/shelfo-iOS-Default-1024x1024@1x.png"
  min_sdk_android: 21
  adaptive_icon_foreground_inset: 16

  adaptive_icon_background_color: "#FFFFFF"
  adaptive_icon_foreground_color: "#16A34A"
  adaptive_icon_background: "assets/logo/bg.png"
  adaptive_icon_foreground: "assets/logo/shelfo_app_logo_icon.png"
  adaptive_monochrome_image: "assets/logo/shelfo_app_logo_icon.svg"
  web:
    generate: true
    image_path: "assets/logo/shelfo-iOS-Dark-1024x1024@1x.png"
    background_color: "#FFFFFF"
    theme_color: "#16A34A"
  macos:
    generate: true
    image_path: "assets/logo/shelfo-iOS-Default-1024x1024@1x.png"
