// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shelfo/models/brand/brand_model.dart';
import 'package:shelfo/models/business/business_model.dart';
import 'package:shelfo/models/category/category_model.dart';
import 'package:shelfo/models/currency/currency.dart';
import 'package:shelfo/models/customer/customer_model.dart';
import 'package:shelfo/models/invoice/invoice_config_model.dart';
import 'package:shelfo/models/notification/notification_model.dart';
import 'package:shelfo/models/policy/policy_model.dart';
import 'package:shelfo/models/product/product_model.dart';
import 'package:shelfo/models/purchase/purchase_item_model.dart';
import 'package:shelfo/models/purchase/purchase_order_model.dart';
import 'package:shelfo/models/sale/sale_item_model.dart';
import 'package:shelfo/models/sale/sale_model.dart';
import 'package:shelfo/models/sale/sales_order_model.dart';
import 'package:shelfo/models/service_job/service_job_model.dart';
import 'package:shelfo/models/tax/tax_config_model.dart';
import 'package:shelfo/models/tax/tax_pricing_mode.dart';
import 'package:shelfo/models/vendor/vendor_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BrandAdapter());
    registerAdapter(BusinessAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CurrencyAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(CustomerTypeAdapter());
    registerAdapter(InvoiceConfigAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(PolicyAdapter());
    registerAdapter(PolicyTypeAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductTypeAdapter());
    registerAdapter(PurchaseItemAdapter());
    registerAdapter(PurchaseOrderAdapter());
    registerAdapter(PurchaseOrderStatusAdapter());
    registerAdapter(SaleAdapter());
    registerAdapter(SaleItemAdapter());
    registerAdapter(SalesOrderAdapter());
    registerAdapter(SalesOrderStatusAdapter());
    registerAdapter(ServiceJobAdapter());
    registerAdapter(ServiceJobPriorityAdapter());
    registerAdapter(ServiceJobStatusAdapter());
    registerAdapter(TaxConfigAdapter());
    registerAdapter(TaxPricingModeAdapter());
    registerAdapter(VendorAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BrandAdapter());
    registerAdapter(BusinessAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CurrencyAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(CustomerTypeAdapter());
    registerAdapter(InvoiceConfigAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(PolicyAdapter());
    registerAdapter(PolicyTypeAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductTypeAdapter());
    registerAdapter(PurchaseItemAdapter());
    registerAdapter(PurchaseOrderAdapter());
    registerAdapter(PurchaseOrderStatusAdapter());
    registerAdapter(SaleAdapter());
    registerAdapter(SaleItemAdapter());
    registerAdapter(SalesOrderAdapter());
    registerAdapter(SalesOrderStatusAdapter());
    registerAdapter(ServiceJobAdapter());
    registerAdapter(ServiceJobPriorityAdapter());
    registerAdapter(ServiceJobStatusAdapter());
    registerAdapter(TaxConfigAdapter());
    registerAdapter(TaxPricingModeAdapter());
    registerAdapter(VendorAdapter());
  }
}
